version: "3"
services:
  reverseproxy:
    image: cipher97/reverseproxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend-user
      - backend-feed
    backend-user:
      image: cipher97/udagram-user-api
      environment:
        POSTGRESS_USERNAME: $POSTGRESS_USERNAME
        POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD
        POSTGRESS_DB: $POSTGRESS_DB
        POSTGRESS_HOST: $POSTGRESS_HOST
        AWS_REGION: $AWS_REGION
        AWS_PROFILE: $AWS_PROFILE
        AWS_BUCKET: $AWS_BUCKET
        JWT_SECRET: $JWT_SECRET
        URL: "http://localhost:8100"
    backend-feed:
      image: cipher97/udagram-feed-api
      volumes:
        - $HOME/.aws:/root/.aws
      environment:
        POSTGRESS_USERNAME: $POSTGRESS_USERNAME
        POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD
        POSTGRESS_DB: $POSTGRESS_DB
        POSTGRESS_HOST: $POSTGRESS_HOST
        AWS_REGION: $AWS_REGION
        AWS_PROFILE: $AWS_PROFILE
        AWS_BUCKET: $AWS_BUCKET
        JWT_SECRET: $JWT_SECRET
        URL: "http://localhost:8100"
    frontend:
      image: cipher97/udagram-frontend:local
      ports:
        - "8100:80"
